# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simcpp <- function(dt, l, mc) {
    invisible(.Call('_IMPACTncdJapan_simcpp', PACKAGE = 'IMPACTncdJapan', dt, l, mc))
}

