// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// simcpp
void simcpp(DataFrame dt, const List l, const int mc);
RcppExport SEXP _IMPACTncdJapan_simcpp(SEXP dtSEXP, SEXP lSEXP, SEXP mcSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< const List >::type l(lSEXP);
    Rcpp::traits::input_parameter< const int >::type mc(mcSEXP);
    simcpp(dt, l, mc);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_IMPACTncdJapan_simcpp", (DL_FUNC) &_IMPACTncdJapan_simcpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_IMPACTncdJapan(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
