name: Build Push prerequisite.IMPACTncdJPN


# NOTE the following logic is disabled because it cannot be used to synchronise
# this workflow with Build Push impactncdjpn. Build Push impactncdjpn need to
# run after this workflow.


# on:
#   push:
#     paths:
#       - docker_setup/Dockerfile.prerequisite.IMPACTncdJPN
#       - docker_setup/apt-packages.txt
#       - docker_setup/r-packages.txt
#       - docker_setup/entrypoint.sh
#       - .github/workflows/setup_dev_docker_env.yml

on:
  push:

jobs:
  run_if_needed:
    runs-on: ubuntu-latest
    if: ${{ 
          contains(join(github.event.commits.*.modified, ','), 'docker_setup/Dockerfile.prerequisite.IMPACTncdJPN') ||
          contains(join(github.event.commits.*.modified, ','), 'docker_setup/apt-packages.txt') ||
          contains(join(github.event.commits.*.modified, ','), 'docker_setup/r-packages.txt') ||
          contains(join(github.event.commits.*.modified, ','), 'docker_setup/entrypoint.sh') ||
          contains(join(github.event.commits.*.modified, ','), '.github/workflows/build_push_prerequisite_impactncdjpn.yml')
        }}
    steps:
      - run: echo "Build Push prerequisite.impactncdjpn is running because relevant files changed."

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: docker_setup # Set the build context to the docker_setup directory
          push: true
          no-cache: true # Ensures no cache is used during the build
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/prerequisite.impactncdjpn:${{ github.ref_name }}
          file: docker_setup/Dockerfile.prerequisite.IMPACTncdJPN