name: Build Push IMPACTncdJPN

on:
  # Only run after the prerequisite workflow finishes
  workflow_run:
    workflows: ["Build Push prerequisite.IMPACTncdJPN"]
    types:
      - completed

jobs:
  build:
    # only proceed if the prerequisite completed successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # checkout exactly the commit that ran in the prerequisite
          ref: ${{ github.event.workflow_run.head_sha }}

      # Replace default ':local' tag in Dockerfile with the triggering branch name
      # (this change is ephemeral in the workflow runner; it won’t be pushed back)
      - name: Update base image tag
        run: |
          sed -i "s|^FROM chriskypri/prerequisite.impactncdjpn:.*|FROM chriskypri/prerequisite.impactncdjpn:${{ github.ref_name }}|" docker_setup/Dockerfile.IMPACTncdJPN

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: docker_setup # Set the build context to the docker_setup directory
          push: true
          no-cache: true # Ensures no cache is used during the build
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/impactncdjpn:${{ github.ref_name }}
          file: docker_setup/Dockerfile.IMPACTncdJPN