name: Setup Dev Docker Environment

on:
  push:
    paths:
      - docker_setup/Dockerfile.prerequisite.IMPACTncdJPN
      - docker_setup/apt-packages.txt
      - docker_setup/r-packages.txt
      - docker_setup/entrypoint.sh

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          no-cache: true # Ensures no cache is used during the build
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/impactncd-japan-r-prerequisite:${{ github.ref_name }}
          file: docker_setup/Dockerfile.prerequisite.IMPACTncdJPN